spring:
  datasource:
    url: jdbc:mariadb://35.238.83.215:3306/DLT
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Player!@1004
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update